### ISSUE TITLE
ili9xxx missing "invert_colors: false" + more

### ISSUE THREAD

**Issue by HauptlingHD** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#19]
I don't know if this has been a recent change, but the minimum configuration of ili9xxx needs to have the value invert_colors set. If it is not present, ESPHome will throw an error.

Even after fixing this by adding "invert_colors: false" after line 1667, I still get an error:

```
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1018, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1005, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 434, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 195, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 213, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 352, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 305, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 720, in copy_files
    repo_dir, _ = git.clone_or_update(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/git.py", line 92, in clone_or_update
    old_sha = run_git_command(["git", "rev-parse", "HEAD"], str(repo_dir))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/git.py", line 32, in run_git_command
    raise cv.Invalid(err_str)
voluptuous.error.Invalid: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by AlmostInteractive** [comment]
I've fallen behind in my updates while working on other projects.  I'll try to get around to updating my HA and ESPHome versions and then I'll get this fixed.

**Comment by AlmostInteractive** [comment]
Thanks and (finally) fixed.
